version: "3.7"
services:
  app:
    build: .
    command: "/bin/sh -c 'poetry run ./manage.py runserver 0.0.0.0:8000 --nostatic'"
    ports:
      - "8000:8000"
  heroku:
    # run `apk add docker` before running heroku commands
    image: sue445/heroku-cli
    working_dir: /workspace
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock:rw